<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ServiceHub</RootNamespace>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <Configurations>Debug;Release;Rsharp_app_release;mzkit_win32;MEMI-Desktop</Configurations>
    <Platforms>AnyCPU;ARM32;x64</Platforms>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='mzkit_win32|net10.0-windows|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <DocumentationFile>ServiceHub.xml</DocumentationFile>
    <RemoveIntegerChecks>true</RemoveIntegerChecks>
    <Optimize>false</Optimize>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <DefineDebug>false</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <OutputPath>../../../../../dist\bin\Rstudio\host\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows|AnyCPU'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows|ARM32'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows|x64'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows|AnyCPU'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows|ARM32'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows|x64'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Rsharp_app_release|net10.0-windows|AnyCPU'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Rsharp_app_release|net10.0-windows|ARM32'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Rsharp_app_release|net10.0-windows|x64'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='mzkit_win32|net10.0-windows|AnyCPU'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='mzkit_win32|net10.0-windows|ARM32'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='mzkit_win32|net10.0-windows|x64'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MEMI-Desktop|net10.0-windows|AnyCPU'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MEMI-Desktop|net10.0-windows|ARM32'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MEMI-Desktop|net10.0-windows|x64'">
      <OutputPath>G:\mzkit\dist\bin\Rstudio\host</OutputPath>
    </PropertyGroup>
  

  
  
  <ItemGroup>
    <Compile Remove="logs\**" />
    <EmbeddedResource Remove="logs\**" />
    <None Remove="logs\**" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
    <PackageReference Include="System.Drawing.Primitives" Version="4.3.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\Erica\src\HEView\HEView.vbproj" />
    <ProjectReference Include="..\..\..\..\..\..\Erica\src\SingleCell\SingleExpression\SingleExpression.vbproj" />
    <ProjectReference Include="..\..\..\..\..\..\GCModeller\src\R-sharp\R#\Rsharp-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\..\..\..\GCModeller\src\runtime\Darwinism\src\computing\IPCDriver\IPCDriver.vbproj" />
    <ProjectReference Include="..\..\..\..\..\..\GCModeller\src\runtime\Darwinism\src\computing\Parallel\parallel-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\..\..\..\GCModeller\src\runtime\Darwinism\src\networking\networking.vbproj" />
    <ProjectReference Include="..\..\..\..\..\..\GCModeller\src\runtime\httpd\src\Flute\Flute.NET5.vbproj" />
    <ProjectReference Include="..\..\..\..\..\..\GCModeller\src\runtime\sciBASIC#\Data\BinaryData\BinaryData\binarydata-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\..\..\..\GCModeller\src\runtime\sciBASIC#\Data_science\MachineLearning\MachineLearning.Data.Extensions\MachineLearning.Data.Extensions.vbproj" />
    <ProjectReference Include="..\..\..\..\..\..\GCModeller\src\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\..\..\assembly\assembly\assembly-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\..\assembly\Comprehensive\Comprehensive.NET5.vbproj" />
    <ProjectReference Include="..\..\..\..\assembly\mzPackExtensions\mzPackExtensions.NET5.vbproj" />
    <ProjectReference Include="..\..\..\..\assembly\mzPack\mzpack.NET5.vbproj" />
    <ProjectReference Include="..\..\..\..\mzmath\ms2_math-core\mzmath-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\..\visualize\MsImaging\MsImaging.NET5.vbproj" />
    <ProjectReference Include="..\..\..\..\visualize\TissueMorphology\TissueMorphology.vbproj" />
  </ItemGroup>
  
  <Import Project="..\..\..\..\..\Rscript\Library\mzkit_app\src\mzkit.interopArguments\mzkit.interopArguments.projitems" Label="Shared" />



  

</Project>
